export default {
    COMMIT_SET_SELETED_TRACKINGS: "addTrackings",
    POSTMESSAGER_CHANGE_ID: "changeId",
    POSTMESSAGER_ALL_TRACKINGS: "getAllTrackings",
    POSTMESSAGER_RESOLVE_TRACKINGS: "resolveTrackings",
    POSTMESSAGER_SET_STORAGE: "setStorage",
    POSTMESSAGER_GET_STORAGE: "getStorage",
    POSTMESSAGER_RESOLVE_STORAGE: "resolveStorage",
    POSTMESSAGER_INSPECT_ELEMENTS: "inspectElements",
    POSTMESSAGER_GET_INSPECT_ELEMENTS: "getInspectElements",
    POSTMESSAGER_GET_ACTIVE_USER: "getActiveUser",
    POSTMESSAGER_RESOLVE_ACTIVE_USER: "resolveActiveUser",
}